spring:
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/user399031/IToker-config.git
          search-paths: respo
          username: 1120264714@qq.com
          password: dage960815

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/